name: Github Actions tutorial

on:
  push:
    branches:
      -main



  workflow_dispatch:

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: Checking out Github Repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Installing package list
        run: apt list --installed
      - name: Run Pytest Selenium Script
        run: |
          pip install -r requirements.txt
          cd TestCases
          pytest -vs TestTutorial.py
          
