name: Selenium Grid tutorial

on:
  schedule:
    - cron: '00 01 * * *'
#  push:
#    branches:
#      -main

  workflow_dispatch:

env:
  PLAN_NAME: Selenium Grid tutorial Pytest

jobs:
  build:
    runs-on:  ubuntu-latest
    env:
      JOB_NAME: build

#    services:
#      chrome:
#        image: selenium/node-chrome:4.8.0-20230210
#        shm_size: 2gb
#        depends_on:
#          - selenium-hub
#        environment:
#          - SE_EVENT_BUS_HOST=selenium-hub
#          - SE_EVENT_BUS_PUBLISH_PORT=4442
#          - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#
#        firefox:
#          image: selenium/node-firefox:4.8.0-20230210
#          shm_size: 2gb
#          depends_on:
#            - selenium-hub
#          environment:
#            - SE_EVENT_BUS_HOST=selenium-hub
#            - SE_EVENT_BUS_PUBLISH_PORT=4442
#            - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
#
#        selenium-hub:
#          image: selenium/hub:4.8.0-20230210
#          container_name: selenium-hub
#          ports:
#            - "4442:4442"
#            - "4443:4443"
#            - "4444:4444"

    steps:

      - name: Checking out Github Repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Docker Compose
        run: |
          docker-compose up -d

      - name: CURL and Update apt
        run: |
          sudo apt update && sudo apt upgrade -y
          curl http://127.0.0.1:4444/wd/hub/status

      - name: Install Virtualenv, Dependencies and Run Pytest
        run: |
          docker ps -a
          ifconfig
          ip addr
          pip install -r requirements.txt
          pytest --version
          cd TestCases
          python -m pytest -vs TestSeleniumGrid.py

      - name: Output Result
        uses: actions/upload-artifact@v3
        with:
          name: Output Screenshot
          path: TestCases/output/screen.png


