name: Github Actions tutorial

on:
  push:
    branches:
      -main



  workflow_dispatch:

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: Checking out Github Repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Installing package list
        run: apt list --installed
      - name: Installing Chrome Browser
        uses: browser-actions/setup-chrome@v1

      - name: Download Chrome, Virtualenv and Packages
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          google-chrome --version
          chrome --version
          pip install virtualenv
          virtualenv --version
          virtualenv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Pytest
          cd TestCases
          pytest -vs TestTutorial.py

      - name: Output Result
        uses: actions/upload-artifact@v3
        with:
          name: Output Screenshot
          path: output/screen.png
          
